# Generated by Django 3.0.7 on 2020-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
