# Generated by Django 3.0.7 on 2020-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0002_document_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
