# Generated by Django 3.0.7 on 2020-07-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebApp', '0003_auto_20200705_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='document',
            name='Phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
